package protos;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protos/proto_importer.proto

public final class ProtoImporter {
  private ProtoImporter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImporterRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImporterRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ImporterRequest.Operation operation = 1;</code>
     * @return The enum numeric value on the wire for operation.
     */
    int getOperationValue();
    /**
     * <code>.ImporterRequest.Operation operation = 1;</code>
     * @return The operation.
     */
    ProtoImporter.ImporterRequest.Operation getOperation();

    /**
     * <code>string manufacturer = 2;</code>
     * @return The manufacturer.
     */
    java.lang.String getManufacturer();
    /**
     * <code>string manufacturer = 2;</code>
     * @return The bytes for manufacturer.
     */
    com.google.protobuf.ByteString
        getManufacturerBytes();

    /**
     * <code>string importer = 3;</code>
     * @return The importer.
     */
    java.lang.String getImporter();
    /**
     * <code>string importer = 3;</code>
     * @return The bytes for importer.
     */
    com.google.protobuf.ByteString
        getImporterBytes();

    /**
     * <code>string product = 4;</code>
     * @return The product.
     */
    java.lang.String getProduct();
    /**
     * <code>string product = 4;</code>
     * @return The bytes for product.
     */
    com.google.protobuf.ByteString
        getProductBytes();

    /**
     * <code>int32 quantity = 5;</code>
     * @return The quantity.
     */
    int getQuantity();

    /**
     * <code>float price = 6;</code>
     * @return The price.
     */
    float getPrice();
  }
  /**
   * Protobuf type {@code ImporterRequest}
   */
  public  static final class ImporterRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImporterRequest)
      ImporterRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImporterRequest.newBuilder() to construct.
    private ImporterRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImporterRequest() {
      operation_ = 0;
      manufacturer_ = "";
      importer_ = "";
      product_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ImporterRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImporterRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              operation_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              manufacturer_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              importer_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              product_ = s;
              break;
            }
            case 40: {

              quantity_ = input.readInt32();
              break;
            }
            case 53: {

              price_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoImporter.internal_static_ImporterRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoImporter.internal_static_ImporterRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoImporter.ImporterRequest.class, ProtoImporter.ImporterRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code ImporterRequest.Operation}
     */
    public enum Operation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MAKE_BID = 0;</code>
       */
      MAKE_BID(0),
      /**
       * <code>LIST_MANUFACTURERS = 1;</code>
       */
      LIST_MANUFACTURERS(1),
      /**
       * <code>LIST_PRODUCTS = 2;</code>
       */
      LIST_PRODUCTS(2),
      /**
       * <code>LIST_BIDS = 3;</code>
       */
      LIST_BIDS(3),
      /**
       * <code>CHECK_HISTORY = 4;</code>
       */
      CHECK_HISTORY(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MAKE_BID = 0;</code>
       */
      public static final int MAKE_BID_VALUE = 0;
      /**
       * <code>LIST_MANUFACTURERS = 1;</code>
       */
      public static final int LIST_MANUFACTURERS_VALUE = 1;
      /**
       * <code>LIST_PRODUCTS = 2;</code>
       */
      public static final int LIST_PRODUCTS_VALUE = 2;
      /**
       * <code>LIST_BIDS = 3;</code>
       */
      public static final int LIST_BIDS_VALUE = 3;
      /**
       * <code>CHECK_HISTORY = 4;</code>
       */
      public static final int CHECK_HISTORY_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Operation valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Operation forNumber(int value) {
        switch (value) {
          case 0: return MAKE_BID;
          case 1: return LIST_MANUFACTURERS;
          case 2: return LIST_PRODUCTS;
          case 3: return LIST_BIDS;
          case 4: return CHECK_HISTORY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Operation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
              public Operation findValueByNumber(int number) {
                return Operation.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ProtoImporter.ImporterRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final Operation[] VALUES = values();

      public static Operation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Operation(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ImporterRequest.Operation)
    }

    public static final int OPERATION_FIELD_NUMBER = 1;
    private int operation_;
    /**
     * <code>.ImporterRequest.Operation operation = 1;</code>
     * @return The enum numeric value on the wire for operation.
     */
    public int getOperationValue() {
      return operation_;
    }
    /**
     * <code>.ImporterRequest.Operation operation = 1;</code>
     * @return The operation.
     */
    public ProtoImporter.ImporterRequest.Operation getOperation() {
      @SuppressWarnings("deprecation")
      ProtoImporter.ImporterRequest.Operation result = ProtoImporter.ImporterRequest.Operation.valueOf(operation_);
      return result == null ? ProtoImporter.ImporterRequest.Operation.UNRECOGNIZED : result;
    }

    public static final int MANUFACTURER_FIELD_NUMBER = 2;
    private volatile java.lang.Object manufacturer_;
    /**
     * <code>string manufacturer = 2;</code>
     * @return The manufacturer.
     */
    public java.lang.String getManufacturer() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        manufacturer_ = s;
        return s;
      }
    }
    /**
     * <code>string manufacturer = 2;</code>
     * @return The bytes for manufacturer.
     */
    public com.google.protobuf.ByteString
        getManufacturerBytes() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manufacturer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMPORTER_FIELD_NUMBER = 3;
    private volatile java.lang.Object importer_;
    /**
     * <code>string importer = 3;</code>
     * @return The importer.
     */
    public java.lang.String getImporter() {
      java.lang.Object ref = importer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        importer_ = s;
        return s;
      }
    }
    /**
     * <code>string importer = 3;</code>
     * @return The bytes for importer.
     */
    public com.google.protobuf.ByteString
        getImporterBytes() {
      java.lang.Object ref = importer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        importer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCT_FIELD_NUMBER = 4;
    private volatile java.lang.Object product_;
    /**
     * <code>string product = 4;</code>
     * @return The product.
     */
    public java.lang.String getProduct() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        product_ = s;
        return s;
      }
    }
    /**
     * <code>string product = 4;</code>
     * @return The bytes for product.
     */
    public com.google.protobuf.ByteString
        getProductBytes() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        product_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 5;
    private int quantity_;
    /**
     * <code>int32 quantity = 5;</code>
     * @return The quantity.
     */
    public int getQuantity() {
      return quantity_;
    }

    public static final int PRICE_FIELD_NUMBER = 6;
    private float price_;
    /**
     * <code>float price = 6;</code>
     * @return The price.
     */
    public float getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (operation_ != ProtoImporter.ImporterRequest.Operation.MAKE_BID.getNumber()) {
        output.writeEnum(1, operation_);
      }
      if (!getManufacturerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, manufacturer_);
      }
      if (!getImporterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, importer_);
      }
      if (!getProductBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, product_);
      }
      if (quantity_ != 0) {
        output.writeInt32(5, quantity_);
      }
      if (price_ != 0F) {
        output.writeFloat(6, price_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (operation_ != ProtoImporter.ImporterRequest.Operation.MAKE_BID.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, operation_);
      }
      if (!getManufacturerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, manufacturer_);
      }
      if (!getImporterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, importer_);
      }
      if (!getProductBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, product_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, quantity_);
      }
      if (price_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoImporter.ImporterRequest)) {
        return super.equals(obj);
      }
      ProtoImporter.ImporterRequest other = (ProtoImporter.ImporterRequest) obj;

      if (operation_ != other.operation_) return false;
      if (!getManufacturer()
          .equals(other.getManufacturer())) return false;
      if (!getImporter()
          .equals(other.getImporter())) return false;
      if (!getProduct()
          .equals(other.getProduct())) return false;
      if (getQuantity()
          != other.getQuantity()) return false;
      if (java.lang.Float.floatToIntBits(getPrice())
          != java.lang.Float.floatToIntBits(
              other.getPrice())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPERATION_FIELD_NUMBER;
      hash = (53 * hash) + operation_;
      hash = (37 * hash) + MANUFACTURER_FIELD_NUMBER;
      hash = (53 * hash) + getManufacturer().hashCode();
      hash = (37 * hash) + IMPORTER_FIELD_NUMBER;
      hash = (53 * hash) + getImporter().hashCode();
      hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
      hash = (53 * hash) + getProduct().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPrice());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoImporter.ImporterRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoImporter.ImporterRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoImporter.ImporterRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoImporter.ImporterRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoImporter.ImporterRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoImporter.ImporterRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoImporter.ImporterRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoImporter.ImporterRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoImporter.ImporterRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoImporter.ImporterRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoImporter.ImporterRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoImporter.ImporterRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoImporter.ImporterRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ImporterRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImporterRequest)
        ProtoImporter.ImporterRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoImporter.internal_static_ImporterRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoImporter.internal_static_ImporterRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoImporter.ImporterRequest.class, ProtoImporter.ImporterRequest.Builder.class);
      }

      // Construct using ProtoImporter.ImporterRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        operation_ = 0;

        manufacturer_ = "";

        importer_ = "";

        product_ = "";

        quantity_ = 0;

        price_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoImporter.internal_static_ImporterRequest_descriptor;
      }

      @java.lang.Override
      public ProtoImporter.ImporterRequest getDefaultInstanceForType() {
        return ProtoImporter.ImporterRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ProtoImporter.ImporterRequest build() {
        ProtoImporter.ImporterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProtoImporter.ImporterRequest buildPartial() {
        ProtoImporter.ImporterRequest result = new ProtoImporter.ImporterRequest(this);
        result.operation_ = operation_;
        result.manufacturer_ = manufacturer_;
        result.importer_ = importer_;
        result.product_ = product_;
        result.quantity_ = quantity_;
        result.price_ = price_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoImporter.ImporterRequest) {
          return mergeFrom((ProtoImporter.ImporterRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoImporter.ImporterRequest other) {
        if (other == ProtoImporter.ImporterRequest.getDefaultInstance()) return this;
        if (other.operation_ != 0) {
          setOperationValue(other.getOperationValue());
        }
        if (!other.getManufacturer().isEmpty()) {
          manufacturer_ = other.manufacturer_;
          onChanged();
        }
        if (!other.getImporter().isEmpty()) {
          importer_ = other.importer_;
          onChanged();
        }
        if (!other.getProduct().isEmpty()) {
          product_ = other.product_;
          onChanged();
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        if (other.getPrice() != 0F) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoImporter.ImporterRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoImporter.ImporterRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int operation_ = 0;
      /**
       * <code>.ImporterRequest.Operation operation = 1;</code>
       * @return The enum numeric value on the wire for operation.
       */
      public int getOperationValue() {
        return operation_;
      }
      /**
       * <code>.ImporterRequest.Operation operation = 1;</code>
       * @param value The enum numeric value on the wire for operation to set.
       * @return This builder for chaining.
       */
      public Builder setOperationValue(int value) {
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ImporterRequest.Operation operation = 1;</code>
       * @return The operation.
       */
      public ProtoImporter.ImporterRequest.Operation getOperation() {
        @SuppressWarnings("deprecation")
        ProtoImporter.ImporterRequest.Operation result = ProtoImporter.ImporterRequest.Operation.valueOf(operation_);
        return result == null ? ProtoImporter.ImporterRequest.Operation.UNRECOGNIZED : result;
      }
      /**
       * <code>.ImporterRequest.Operation operation = 1;</code>
       * @param value The operation to set.
       * @return This builder for chaining.
       */
      public Builder setOperation(ProtoImporter.ImporterRequest.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        operation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ImporterRequest.Operation operation = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperation() {
        
        operation_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object manufacturer_ = "";
      /**
       * <code>string manufacturer = 2;</code>
       * @return The manufacturer.
       */
      public java.lang.String getManufacturer() {
        java.lang.Object ref = manufacturer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          manufacturer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string manufacturer = 2;</code>
       * @return The bytes for manufacturer.
       */
      public com.google.protobuf.ByteString
          getManufacturerBytes() {
        java.lang.Object ref = manufacturer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          manufacturer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string manufacturer = 2;</code>
       * @param value The manufacturer to set.
       * @return This builder for chaining.
       */
      public Builder setManufacturer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        manufacturer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string manufacturer = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearManufacturer() {
        
        manufacturer_ = getDefaultInstance().getManufacturer();
        onChanged();
        return this;
      }
      /**
       * <code>string manufacturer = 2;</code>
       * @param value The bytes for manufacturer to set.
       * @return This builder for chaining.
       */
      public Builder setManufacturerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        manufacturer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object importer_ = "";
      /**
       * <code>string importer = 3;</code>
       * @return The importer.
       */
      public java.lang.String getImporter() {
        java.lang.Object ref = importer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          importer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string importer = 3;</code>
       * @return The bytes for importer.
       */
      public com.google.protobuf.ByteString
          getImporterBytes() {
        java.lang.Object ref = importer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          importer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string importer = 3;</code>
       * @param value The importer to set.
       * @return This builder for chaining.
       */
      public Builder setImporter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        importer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string importer = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearImporter() {
        
        importer_ = getDefaultInstance().getImporter();
        onChanged();
        return this;
      }
      /**
       * <code>string importer = 3;</code>
       * @param value The bytes for importer to set.
       * @return This builder for chaining.
       */
      public Builder setImporterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        importer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object product_ = "";
      /**
       * <code>string product = 4;</code>
       * @return The product.
       */
      public java.lang.String getProduct() {
        java.lang.Object ref = product_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          product_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string product = 4;</code>
       * @return The bytes for product.
       */
      public com.google.protobuf.ByteString
          getProductBytes() {
        java.lang.Object ref = product_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          product_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string product = 4;</code>
       * @param value The product to set.
       * @return This builder for chaining.
       */
      public Builder setProduct(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        product_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string product = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearProduct() {
        
        product_ = getDefaultInstance().getProduct();
        onChanged();
        return this;
      }
      /**
       * <code>string product = 4;</code>
       * @param value The bytes for product to set.
       * @return This builder for chaining.
       */
      public Builder setProductBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        product_ = value;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>int32 quantity = 5;</code>
       * @return The quantity.
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>int32 quantity = 5;</code>
       * @param value The quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantity(int value) {
        
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantity() {
        
        quantity_ = 0;
        onChanged();
        return this;
      }

      private float price_ ;
      /**
       * <code>float price = 6;</code>
       * @return The price.
       */
      public float getPrice() {
        return price_;
      }
      /**
       * <code>float price = 6;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(float value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float price = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        
        price_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImporterRequest)
    }

    // @@protoc_insertion_point(class_scope:ImporterRequest)
    private static final ProtoImporter.ImporterRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoImporter.ImporterRequest();
    }

    public static ProtoImporter.ImporterRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImporterRequest>
        PARSER = new com.google.protobuf.AbstractParser<ImporterRequest>() {
      @java.lang.Override
      public ImporterRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImporterRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImporterRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImporterRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ProtoImporter.ImporterRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImporterRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImporterRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/protos/proto_importer.proto\"\202\002\n\017Im" +
      "porterRequest\022-\n\toperation\030\001 \001(\0162\032.Impor" +
      "terRequest.Operation\022\024\n\014manufacturer\030\002 \001" +
      "(\t\022\020\n\010importer\030\003 \001(\t\022\017\n\007product\030\004 \001(\t\022\020\n" +
      "\010quantity\030\005 \001(\005\022\r\n\005price\030\006 \001(\002\"f\n\tOperat" +
      "ion\022\014\n\010MAKE_BID\020\000\022\026\n\022LIST_MANUFACTURERS\020" +
      "\001\022\021\n\rLIST_PRODUCTS\020\002\022\r\n\tLIST_BIDS\020\003\022\021\n\rC" +
      "HECK_HISTORY\020\004b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ImporterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImporterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImporterRequest_descriptor,
        new java.lang.String[] { "Operation", "Manufacturer", "Importer", "Product", "Quantity", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
