package protos;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protos/proto_product.proto

public final class ProtoProduct {
  private ProtoProduct() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 min_quantity = 2;</code>
     * @return The minQuantity.
     */
    int getMinQuantity();

    /**
     * <code>int32 max_quantity = 3;</code>
     * @return The maxQuantity.
     */
    int getMaxQuantity();

    /**
     * <code>float min_price = 4;</code>
     * @return The minPrice.
     */
    float getMinPrice();

    /**
     * <code>int32 seconds = 5;</code>
     * @return The seconds.
     */
    int getSeconds();
  }
  /**
   * Protobuf type {@code Product}
   */
  public  static final class Product extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Product)
      ProductOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Product.newBuilder() to construct.
    private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Product() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Product();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Product(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              minQuantity_ = input.readInt32();
              break;
            }
            case 24: {

              maxQuantity_ = input.readInt32();
              break;
            }
            case 37: {

              minPrice_ = input.readFloat();
              break;
            }
            case 40: {

              seconds_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoProduct.internal_static_Product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoProduct.internal_static_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoProduct.Product.class, ProtoProduct.Product.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MIN_QUANTITY_FIELD_NUMBER = 2;
    private int minQuantity_;
    /**
     * <code>int32 min_quantity = 2;</code>
     * @return The minQuantity.
     */
    public int getMinQuantity() {
      return minQuantity_;
    }

    public static final int MAX_QUANTITY_FIELD_NUMBER = 3;
    private int maxQuantity_;
    /**
     * <code>int32 max_quantity = 3;</code>
     * @return The maxQuantity.
     */
    public int getMaxQuantity() {
      return maxQuantity_;
    }

    public static final int MIN_PRICE_FIELD_NUMBER = 4;
    private float minPrice_;
    /**
     * <code>float min_price = 4;</code>
     * @return The minPrice.
     */
    public float getMinPrice() {
      return minPrice_;
    }

    public static final int SECONDS_FIELD_NUMBER = 5;
    private int seconds_;
    /**
     * <code>int32 seconds = 5;</code>
     * @return The seconds.
     */
    public int getSeconds() {
      return seconds_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (minQuantity_ != 0) {
        output.writeInt32(2, minQuantity_);
      }
      if (maxQuantity_ != 0) {
        output.writeInt32(3, maxQuantity_);
      }
      if (minPrice_ != 0F) {
        output.writeFloat(4, minPrice_);
      }
      if (seconds_ != 0) {
        output.writeInt32(5, seconds_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (minQuantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, minQuantity_);
      }
      if (maxQuantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, maxQuantity_);
      }
      if (minPrice_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, minPrice_);
      }
      if (seconds_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, seconds_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoProduct.Product)) {
        return super.equals(obj);
      }
      ProtoProduct.Product other = (ProtoProduct.Product) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getMinQuantity()
          != other.getMinQuantity()) return false;
      if (getMaxQuantity()
          != other.getMaxQuantity()) return false;
      if (java.lang.Float.floatToIntBits(getMinPrice())
          != java.lang.Float.floatToIntBits(
              other.getMinPrice())) return false;
      if (getSeconds()
          != other.getSeconds()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + MIN_QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getMinQuantity();
      hash = (37 * hash) + MAX_QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getMaxQuantity();
      hash = (37 * hash) + MIN_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMinPrice());
      hash = (37 * hash) + SECONDS_FIELD_NUMBER;
      hash = (53 * hash) + getSeconds();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoProduct.Product parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoProduct.Product parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoProduct.Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoProduct.Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoProduct.Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoProduct.Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoProduct.Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoProduct.Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoProduct.Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoProduct.Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoProduct.Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoProduct.Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoProduct.Product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Product)
        ProtoProduct.ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoProduct.internal_static_Product_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoProduct.internal_static_Product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoProduct.Product.class, ProtoProduct.Product.Builder.class);
      }

      // Construct using ProtoProduct.Product.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        minQuantity_ = 0;

        maxQuantity_ = 0;

        minPrice_ = 0F;

        seconds_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoProduct.internal_static_Product_descriptor;
      }

      @java.lang.Override
      public ProtoProduct.Product getDefaultInstanceForType() {
        return ProtoProduct.Product.getDefaultInstance();
      }

      @java.lang.Override
      public ProtoProduct.Product build() {
        ProtoProduct.Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProtoProduct.Product buildPartial() {
        ProtoProduct.Product result = new ProtoProduct.Product(this);
        result.name_ = name_;
        result.minQuantity_ = minQuantity_;
        result.maxQuantity_ = maxQuantity_;
        result.minPrice_ = minPrice_;
        result.seconds_ = seconds_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoProduct.Product) {
          return mergeFrom((ProtoProduct.Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoProduct.Product other) {
        if (other == ProtoProduct.Product.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getMinQuantity() != 0) {
          setMinQuantity(other.getMinQuantity());
        }
        if (other.getMaxQuantity() != 0) {
          setMaxQuantity(other.getMaxQuantity());
        }
        if (other.getMinPrice() != 0F) {
          setMinPrice(other.getMinPrice());
        }
        if (other.getSeconds() != 0) {
          setSeconds(other.getSeconds());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoProduct.Product parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoProduct.Product) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int minQuantity_ ;
      /**
       * <code>int32 min_quantity = 2;</code>
       * @return The minQuantity.
       */
      public int getMinQuantity() {
        return minQuantity_;
      }
      /**
       * <code>int32 min_quantity = 2;</code>
       * @param value The minQuantity to set.
       * @return This builder for chaining.
       */
      public Builder setMinQuantity(int value) {
        
        minQuantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 min_quantity = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinQuantity() {
        
        minQuantity_ = 0;
        onChanged();
        return this;
      }

      private int maxQuantity_ ;
      /**
       * <code>int32 max_quantity = 3;</code>
       * @return The maxQuantity.
       */
      public int getMaxQuantity() {
        return maxQuantity_;
      }
      /**
       * <code>int32 max_quantity = 3;</code>
       * @param value The maxQuantity to set.
       * @return This builder for chaining.
       */
      public Builder setMaxQuantity(int value) {
        
        maxQuantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 max_quantity = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxQuantity() {
        
        maxQuantity_ = 0;
        onChanged();
        return this;
      }

      private float minPrice_ ;
      /**
       * <code>float min_price = 4;</code>
       * @return The minPrice.
       */
      public float getMinPrice() {
        return minPrice_;
      }
      /**
       * <code>float min_price = 4;</code>
       * @param value The minPrice to set.
       * @return This builder for chaining.
       */
      public Builder setMinPrice(float value) {
        
        minPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float min_price = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinPrice() {
        
        minPrice_ = 0F;
        onChanged();
        return this;
      }

      private int seconds_ ;
      /**
       * <code>int32 seconds = 5;</code>
       * @return The seconds.
       */
      public int getSeconds() {
        return seconds_;
      }
      /**
       * <code>int32 seconds = 5;</code>
       * @param value The seconds to set.
       * @return This builder for chaining.
       */
      public Builder setSeconds(int value) {
        
        seconds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 seconds = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeconds() {
        
        seconds_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Product)
    }

    // @@protoc_insertion_point(class_scope:Product)
    private static final ProtoProduct.Product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoProduct.Product();
    }

    public static ProtoProduct.Product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Product>
        PARSER = new com.google.protobuf.AbstractParser<Product>() {
      @java.lang.Override
      public Product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Product(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Product> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Product> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ProtoProduct.Product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/protos/proto_product.proto\"g\n\007Prod" +
      "uct\022\014\n\004name\030\001 \001(\t\022\024\n\014min_quantity\030\002 \001(\005\022" +
      "\024\n\014max_quantity\030\003 \001(\005\022\021\n\tmin_price\030\004 \001(\002" +
      "\022\017\n\007seconds\030\005 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_descriptor,
        new java.lang.String[] { "Name", "MinQuantity", "MaxQuantity", "MinPrice", "Seconds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
