package protos;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protos/proto_bid.proto

public final class ProtoBid {
  private ProtoBid() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BidOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Bid)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string manufacturer = 1;</code>
     * @return The manufacturer.
     */
    java.lang.String getManufacturer();
    /**
     * <code>string manufacturer = 1;</code>
     * @return The bytes for manufacturer.
     */
    com.google.protobuf.ByteString
        getManufacturerBytes();

    /**
     * <code>string importer = 2;</code>
     * @return The importer.
     */
    java.lang.String getImporter();
    /**
     * <code>string importer = 2;</code>
     * @return The bytes for importer.
     */
    com.google.protobuf.ByteString
        getImporterBytes();

    /**
     * <code>string product = 3;</code>
     * @return The product.
     */
    java.lang.String getProduct();
    /**
     * <code>string product = 3;</code>
     * @return The bytes for product.
     */
    com.google.protobuf.ByteString
        getProductBytes();

    /**
     * <code>int32 quantity = 4;</code>
     * @return The quantity.
     */
    int getQuantity();

    /**
     * <code>float price = 5;</code>
     * @return The price.
     */
    float getPrice();
  }
  /**
   * Protobuf type {@code Bid}
   */
  public  static final class Bid extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Bid)
      BidOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Bid.newBuilder() to construct.
    private Bid(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Bid() {
      manufacturer_ = "";
      importer_ = "";
      product_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Bid();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Bid(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              manufacturer_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              importer_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              product_ = s;
              break;
            }
            case 32: {

              quantity_ = input.readInt32();
              break;
            }
            case 45: {

              price_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoBid.internal_static_Bid_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoBid.internal_static_Bid_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoBid.Bid.class, ProtoBid.Bid.Builder.class);
    }

    public static final int MANUFACTURER_FIELD_NUMBER = 1;
    private volatile java.lang.Object manufacturer_;
    /**
     * <code>string manufacturer = 1;</code>
     * @return The manufacturer.
     */
    public java.lang.String getManufacturer() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        manufacturer_ = s;
        return s;
      }
    }
    /**
     * <code>string manufacturer = 1;</code>
     * @return The bytes for manufacturer.
     */
    public com.google.protobuf.ByteString
        getManufacturerBytes() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manufacturer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMPORTER_FIELD_NUMBER = 2;
    private volatile java.lang.Object importer_;
    /**
     * <code>string importer = 2;</code>
     * @return The importer.
     */
    public java.lang.String getImporter() {
      java.lang.Object ref = importer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        importer_ = s;
        return s;
      }
    }
    /**
     * <code>string importer = 2;</code>
     * @return The bytes for importer.
     */
    public com.google.protobuf.ByteString
        getImporterBytes() {
      java.lang.Object ref = importer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        importer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCT_FIELD_NUMBER = 3;
    private volatile java.lang.Object product_;
    /**
     * <code>string product = 3;</code>
     * @return The product.
     */
    public java.lang.String getProduct() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        product_ = s;
        return s;
      }
    }
    /**
     * <code>string product = 3;</code>
     * @return The bytes for product.
     */
    public com.google.protobuf.ByteString
        getProductBytes() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        product_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 4;
    private int quantity_;
    /**
     * <code>int32 quantity = 4;</code>
     * @return The quantity.
     */
    public int getQuantity() {
      return quantity_;
    }

    public static final int PRICE_FIELD_NUMBER = 5;
    private float price_;
    /**
     * <code>float price = 5;</code>
     * @return The price.
     */
    public float getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getManufacturerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, manufacturer_);
      }
      if (!getImporterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, importer_);
      }
      if (!getProductBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, product_);
      }
      if (quantity_ != 0) {
        output.writeInt32(4, quantity_);
      }
      if (price_ != 0F) {
        output.writeFloat(5, price_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getManufacturerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, manufacturer_);
      }
      if (!getImporterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, importer_);
      }
      if (!getProductBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, product_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, quantity_);
      }
      if (price_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoBid.Bid)) {
        return super.equals(obj);
      }
      ProtoBid.Bid other = (ProtoBid.Bid) obj;

      if (!getManufacturer()
          .equals(other.getManufacturer())) return false;
      if (!getImporter()
          .equals(other.getImporter())) return false;
      if (!getProduct()
          .equals(other.getProduct())) return false;
      if (getQuantity()
          != other.getQuantity()) return false;
      if (java.lang.Float.floatToIntBits(getPrice())
          != java.lang.Float.floatToIntBits(
              other.getPrice())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MANUFACTURER_FIELD_NUMBER;
      hash = (53 * hash) + getManufacturer().hashCode();
      hash = (37 * hash) + IMPORTER_FIELD_NUMBER;
      hash = (53 * hash) + getImporter().hashCode();
      hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
      hash = (53 * hash) + getProduct().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPrice());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoBid.Bid parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBid.Bid parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBid.Bid parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBid.Bid parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBid.Bid parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBid.Bid parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBid.Bid parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoBid.Bid parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoBid.Bid parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoBid.Bid parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoBid.Bid parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoBid.Bid parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoBid.Bid prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Bid}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Bid)
        ProtoBid.BidOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoBid.internal_static_Bid_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoBid.internal_static_Bid_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoBid.Bid.class, ProtoBid.Bid.Builder.class);
      }

      // Construct using ProtoBid.Bid.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        manufacturer_ = "";

        importer_ = "";

        product_ = "";

        quantity_ = 0;

        price_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoBid.internal_static_Bid_descriptor;
      }

      @java.lang.Override
      public ProtoBid.Bid getDefaultInstanceForType() {
        return ProtoBid.Bid.getDefaultInstance();
      }

      @java.lang.Override
      public ProtoBid.Bid build() {
        ProtoBid.Bid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProtoBid.Bid buildPartial() {
        ProtoBid.Bid result = new ProtoBid.Bid(this);
        result.manufacturer_ = manufacturer_;
        result.importer_ = importer_;
        result.product_ = product_;
        result.quantity_ = quantity_;
        result.price_ = price_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoBid.Bid) {
          return mergeFrom((ProtoBid.Bid)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoBid.Bid other) {
        if (other == ProtoBid.Bid.getDefaultInstance()) return this;
        if (!other.getManufacturer().isEmpty()) {
          manufacturer_ = other.manufacturer_;
          onChanged();
        }
        if (!other.getImporter().isEmpty()) {
          importer_ = other.importer_;
          onChanged();
        }
        if (!other.getProduct().isEmpty()) {
          product_ = other.product_;
          onChanged();
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        if (other.getPrice() != 0F) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoBid.Bid parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoBid.Bid) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object manufacturer_ = "";
      /**
       * <code>string manufacturer = 1;</code>
       * @return The manufacturer.
       */
      public java.lang.String getManufacturer() {
        java.lang.Object ref = manufacturer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          manufacturer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string manufacturer = 1;</code>
       * @return The bytes for manufacturer.
       */
      public com.google.protobuf.ByteString
          getManufacturerBytes() {
        java.lang.Object ref = manufacturer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          manufacturer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string manufacturer = 1;</code>
       * @param value The manufacturer to set.
       * @return This builder for chaining.
       */
      public Builder setManufacturer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        manufacturer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string manufacturer = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearManufacturer() {
        
        manufacturer_ = getDefaultInstance().getManufacturer();
        onChanged();
        return this;
      }
      /**
       * <code>string manufacturer = 1;</code>
       * @param value The bytes for manufacturer to set.
       * @return This builder for chaining.
       */
      public Builder setManufacturerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        manufacturer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object importer_ = "";
      /**
       * <code>string importer = 2;</code>
       * @return The importer.
       */
      public java.lang.String getImporter() {
        java.lang.Object ref = importer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          importer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string importer = 2;</code>
       * @return The bytes for importer.
       */
      public com.google.protobuf.ByteString
          getImporterBytes() {
        java.lang.Object ref = importer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          importer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string importer = 2;</code>
       * @param value The importer to set.
       * @return This builder for chaining.
       */
      public Builder setImporter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        importer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string importer = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearImporter() {
        
        importer_ = getDefaultInstance().getImporter();
        onChanged();
        return this;
      }
      /**
       * <code>string importer = 2;</code>
       * @param value The bytes for importer to set.
       * @return This builder for chaining.
       */
      public Builder setImporterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        importer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object product_ = "";
      /**
       * <code>string product = 3;</code>
       * @return The product.
       */
      public java.lang.String getProduct() {
        java.lang.Object ref = product_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          product_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string product = 3;</code>
       * @return The bytes for product.
       */
      public com.google.protobuf.ByteString
          getProductBytes() {
        java.lang.Object ref = product_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          product_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string product = 3;</code>
       * @param value The product to set.
       * @return This builder for chaining.
       */
      public Builder setProduct(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        product_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string product = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearProduct() {
        
        product_ = getDefaultInstance().getProduct();
        onChanged();
        return this;
      }
      /**
       * <code>string product = 3;</code>
       * @param value The bytes for product to set.
       * @return This builder for chaining.
       */
      public Builder setProductBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        product_ = value;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>int32 quantity = 4;</code>
       * @return The quantity.
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>int32 quantity = 4;</code>
       * @param value The quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantity(int value) {
        
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantity() {
        
        quantity_ = 0;
        onChanged();
        return this;
      }

      private float price_ ;
      /**
       * <code>float price = 5;</code>
       * @return The price.
       */
      public float getPrice() {
        return price_;
      }
      /**
       * <code>float price = 5;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(float value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float price = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        
        price_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Bid)
    }

    // @@protoc_insertion_point(class_scope:Bid)
    private static final ProtoBid.Bid DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoBid.Bid();
    }

    public static ProtoBid.Bid getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Bid>
        PARSER = new com.google.protobuf.AbstractParser<Bid>() {
      @java.lang.Override
      public Bid parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Bid(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Bid> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Bid> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ProtoBid.Bid getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Bid_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Bid_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/protos/proto_bid.proto\"_\n\003Bid\022\024\n\014m" +
      "anufacturer\030\001 \001(\t\022\020\n\010importer\030\002 \001(\t\022\017\n\007p" +
      "roduct\030\003 \001(\t\022\020\n\010quantity\030\004 \001(\005\022\r\n\005price\030" +
      "\005 \001(\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Bid_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Bid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Bid_descriptor,
        new java.lang.String[] { "Manufacturer", "Importer", "Product", "Quantity", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
