package protos;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protos/proto_manufacturer.proto

public final class ProtoManufacturer {
  private ProtoManufacturer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ManufacturerRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ManufacturerRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string manufacturer = 1;</code>
     * @return The manufacturer.
     */
    java.lang.String getManufacturer();
    /**
     * <code>string manufacturer = 1;</code>
     * @return The bytes for manufacturer.
     */
    com.google.protobuf.ByteString
        getManufacturerBytes();

    /**
     * <code>string product = 2;</code>
     * @return The product.
     */
    java.lang.String getProduct();
    /**
     * <code>string product = 2;</code>
     * @return The bytes for product.
     */
    com.google.protobuf.ByteString
        getProductBytes();

    /**
     * <code>int32 min_quantity = 3;</code>
     * @return The minQuantity.
     */
    int getMinQuantity();

    /**
     * <code>int32 max_quantity = 4;</code>
     * @return The maxQuantity.
     */
    int getMaxQuantity();

    /**
     * <code>float min_price = 5;</code>
     * @return The minPrice.
     */
    float getMinPrice();

    /**
     * <code>int32 seconds = 6;</code>
     * @return The seconds.
     */
    int getSeconds();
  }
  /**
   * Protobuf type {@code ManufacturerRequest}
   */
  public  static final class ManufacturerRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ManufacturerRequest)
      ManufacturerRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ManufacturerRequest.newBuilder() to construct.
    private ManufacturerRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ManufacturerRequest() {
      manufacturer_ = "";
      product_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ManufacturerRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ManufacturerRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              manufacturer_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              product_ = s;
              break;
            }
            case 24: {

              minQuantity_ = input.readInt32();
              break;
            }
            case 32: {

              maxQuantity_ = input.readInt32();
              break;
            }
            case 45: {

              minPrice_ = input.readFloat();
              break;
            }
            case 48: {

              seconds_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoManufacturer.internal_static_ManufacturerRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoManufacturer.internal_static_ManufacturerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoManufacturer.ManufacturerRequest.class, ProtoManufacturer.ManufacturerRequest.Builder.class);
    }

    public static final int MANUFACTURER_FIELD_NUMBER = 1;
    private volatile java.lang.Object manufacturer_;
    /**
     * <code>string manufacturer = 1;</code>
     * @return The manufacturer.
     */
    public java.lang.String getManufacturer() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        manufacturer_ = s;
        return s;
      }
    }
    /**
     * <code>string manufacturer = 1;</code>
     * @return The bytes for manufacturer.
     */
    public com.google.protobuf.ByteString
        getManufacturerBytes() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manufacturer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCT_FIELD_NUMBER = 2;
    private volatile java.lang.Object product_;
    /**
     * <code>string product = 2;</code>
     * @return The product.
     */
    public java.lang.String getProduct() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        product_ = s;
        return s;
      }
    }
    /**
     * <code>string product = 2;</code>
     * @return The bytes for product.
     */
    public com.google.protobuf.ByteString
        getProductBytes() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        product_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MIN_QUANTITY_FIELD_NUMBER = 3;
    private int minQuantity_;
    /**
     * <code>int32 min_quantity = 3;</code>
     * @return The minQuantity.
     */
    public int getMinQuantity() {
      return minQuantity_;
    }

    public static final int MAX_QUANTITY_FIELD_NUMBER = 4;
    private int maxQuantity_;
    /**
     * <code>int32 max_quantity = 4;</code>
     * @return The maxQuantity.
     */
    public int getMaxQuantity() {
      return maxQuantity_;
    }

    public static final int MIN_PRICE_FIELD_NUMBER = 5;
    private float minPrice_;
    /**
     * <code>float min_price = 5;</code>
     * @return The minPrice.
     */
    public float getMinPrice() {
      return minPrice_;
    }

    public static final int SECONDS_FIELD_NUMBER = 6;
    private int seconds_;
    /**
     * <code>int32 seconds = 6;</code>
     * @return The seconds.
     */
    public int getSeconds() {
      return seconds_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getManufacturerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, manufacturer_);
      }
      if (!getProductBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, product_);
      }
      if (minQuantity_ != 0) {
        output.writeInt32(3, minQuantity_);
      }
      if (maxQuantity_ != 0) {
        output.writeInt32(4, maxQuantity_);
      }
      if (minPrice_ != 0F) {
        output.writeFloat(5, minPrice_);
      }
      if (seconds_ != 0) {
        output.writeInt32(6, seconds_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getManufacturerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, manufacturer_);
      }
      if (!getProductBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, product_);
      }
      if (minQuantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, minQuantity_);
      }
      if (maxQuantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, maxQuantity_);
      }
      if (minPrice_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, minPrice_);
      }
      if (seconds_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, seconds_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoManufacturer.ManufacturerRequest)) {
        return super.equals(obj);
      }
      ProtoManufacturer.ManufacturerRequest other = (ProtoManufacturer.ManufacturerRequest) obj;

      if (!getManufacturer()
          .equals(other.getManufacturer())) return false;
      if (!getProduct()
          .equals(other.getProduct())) return false;
      if (getMinQuantity()
          != other.getMinQuantity()) return false;
      if (getMaxQuantity()
          != other.getMaxQuantity()) return false;
      if (java.lang.Float.floatToIntBits(getMinPrice())
          != java.lang.Float.floatToIntBits(
              other.getMinPrice())) return false;
      if (getSeconds()
          != other.getSeconds()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MANUFACTURER_FIELD_NUMBER;
      hash = (53 * hash) + getManufacturer().hashCode();
      hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
      hash = (53 * hash) + getProduct().hashCode();
      hash = (37 * hash) + MIN_QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getMinQuantity();
      hash = (37 * hash) + MAX_QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getMaxQuantity();
      hash = (37 * hash) + MIN_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMinPrice());
      hash = (37 * hash) + SECONDS_FIELD_NUMBER;
      hash = (53 * hash) + getSeconds();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoManufacturer.ManufacturerRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoManufacturer.ManufacturerRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoManufacturer.ManufacturerRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoManufacturer.ManufacturerRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoManufacturer.ManufacturerRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoManufacturer.ManufacturerRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoManufacturer.ManufacturerRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoManufacturer.ManufacturerRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoManufacturer.ManufacturerRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoManufacturer.ManufacturerRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoManufacturer.ManufacturerRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoManufacturer.ManufacturerRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoManufacturer.ManufacturerRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ManufacturerRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ManufacturerRequest)
        ProtoManufacturer.ManufacturerRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoManufacturer.internal_static_ManufacturerRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoManufacturer.internal_static_ManufacturerRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoManufacturer.ManufacturerRequest.class, ProtoManufacturer.ManufacturerRequest.Builder.class);
      }

      // Construct using ProtoManufacturer.ManufacturerRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        manufacturer_ = "";

        product_ = "";

        minQuantity_ = 0;

        maxQuantity_ = 0;

        minPrice_ = 0F;

        seconds_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoManufacturer.internal_static_ManufacturerRequest_descriptor;
      }

      @java.lang.Override
      public ProtoManufacturer.ManufacturerRequest getDefaultInstanceForType() {
        return ProtoManufacturer.ManufacturerRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ProtoManufacturer.ManufacturerRequest build() {
        ProtoManufacturer.ManufacturerRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProtoManufacturer.ManufacturerRequest buildPartial() {
        ProtoManufacturer.ManufacturerRequest result = new ProtoManufacturer.ManufacturerRequest(this);
        result.manufacturer_ = manufacturer_;
        result.product_ = product_;
        result.minQuantity_ = minQuantity_;
        result.maxQuantity_ = maxQuantity_;
        result.minPrice_ = minPrice_;
        result.seconds_ = seconds_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoManufacturer.ManufacturerRequest) {
          return mergeFrom((ProtoManufacturer.ManufacturerRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoManufacturer.ManufacturerRequest other) {
        if (other == ProtoManufacturer.ManufacturerRequest.getDefaultInstance()) return this;
        if (!other.getManufacturer().isEmpty()) {
          manufacturer_ = other.manufacturer_;
          onChanged();
        }
        if (!other.getProduct().isEmpty()) {
          product_ = other.product_;
          onChanged();
        }
        if (other.getMinQuantity() != 0) {
          setMinQuantity(other.getMinQuantity());
        }
        if (other.getMaxQuantity() != 0) {
          setMaxQuantity(other.getMaxQuantity());
        }
        if (other.getMinPrice() != 0F) {
          setMinPrice(other.getMinPrice());
        }
        if (other.getSeconds() != 0) {
          setSeconds(other.getSeconds());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoManufacturer.ManufacturerRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoManufacturer.ManufacturerRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object manufacturer_ = "";
      /**
       * <code>string manufacturer = 1;</code>
       * @return The manufacturer.
       */
      public java.lang.String getManufacturer() {
        java.lang.Object ref = manufacturer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          manufacturer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string manufacturer = 1;</code>
       * @return The bytes for manufacturer.
       */
      public com.google.protobuf.ByteString
          getManufacturerBytes() {
        java.lang.Object ref = manufacturer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          manufacturer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string manufacturer = 1;</code>
       * @param value The manufacturer to set.
       * @return This builder for chaining.
       */
      public Builder setManufacturer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        manufacturer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string manufacturer = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearManufacturer() {
        
        manufacturer_ = getDefaultInstance().getManufacturer();
        onChanged();
        return this;
      }
      /**
       * <code>string manufacturer = 1;</code>
       * @param value The bytes for manufacturer to set.
       * @return This builder for chaining.
       */
      public Builder setManufacturerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        manufacturer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object product_ = "";
      /**
       * <code>string product = 2;</code>
       * @return The product.
       */
      public java.lang.String getProduct() {
        java.lang.Object ref = product_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          product_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string product = 2;</code>
       * @return The bytes for product.
       */
      public com.google.protobuf.ByteString
          getProductBytes() {
        java.lang.Object ref = product_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          product_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string product = 2;</code>
       * @param value The product to set.
       * @return This builder for chaining.
       */
      public Builder setProduct(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        product_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string product = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProduct() {
        
        product_ = getDefaultInstance().getProduct();
        onChanged();
        return this;
      }
      /**
       * <code>string product = 2;</code>
       * @param value The bytes for product to set.
       * @return This builder for chaining.
       */
      public Builder setProductBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        product_ = value;
        onChanged();
        return this;
      }

      private int minQuantity_ ;
      /**
       * <code>int32 min_quantity = 3;</code>
       * @return The minQuantity.
       */
      public int getMinQuantity() {
        return minQuantity_;
      }
      /**
       * <code>int32 min_quantity = 3;</code>
       * @param value The minQuantity to set.
       * @return This builder for chaining.
       */
      public Builder setMinQuantity(int value) {
        
        minQuantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 min_quantity = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinQuantity() {
        
        minQuantity_ = 0;
        onChanged();
        return this;
      }

      private int maxQuantity_ ;
      /**
       * <code>int32 max_quantity = 4;</code>
       * @return The maxQuantity.
       */
      public int getMaxQuantity() {
        return maxQuantity_;
      }
      /**
       * <code>int32 max_quantity = 4;</code>
       * @param value The maxQuantity to set.
       * @return This builder for chaining.
       */
      public Builder setMaxQuantity(int value) {
        
        maxQuantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 max_quantity = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxQuantity() {
        
        maxQuantity_ = 0;
        onChanged();
        return this;
      }

      private float minPrice_ ;
      /**
       * <code>float min_price = 5;</code>
       * @return The minPrice.
       */
      public float getMinPrice() {
        return minPrice_;
      }
      /**
       * <code>float min_price = 5;</code>
       * @param value The minPrice to set.
       * @return This builder for chaining.
       */
      public Builder setMinPrice(float value) {
        
        minPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float min_price = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinPrice() {
        
        minPrice_ = 0F;
        onChanged();
        return this;
      }

      private int seconds_ ;
      /**
       * <code>int32 seconds = 6;</code>
       * @return The seconds.
       */
      public int getSeconds() {
        return seconds_;
      }
      /**
       * <code>int32 seconds = 6;</code>
       * @param value The seconds to set.
       * @return This builder for chaining.
       */
      public Builder setSeconds(int value) {
        
        seconds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 seconds = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeconds() {
        
        seconds_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ManufacturerRequest)
    }

    // @@protoc_insertion_point(class_scope:ManufacturerRequest)
    private static final ProtoManufacturer.ManufacturerRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoManufacturer.ManufacturerRequest();
    }

    public static ProtoManufacturer.ManufacturerRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ManufacturerRequest>
        PARSER = new com.google.protobuf.AbstractParser<ManufacturerRequest>() {
      @java.lang.Override
      public ManufacturerRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ManufacturerRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ManufacturerRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ManufacturerRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ProtoManufacturer.ManufacturerRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ManufacturerRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ManufacturerRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#src/protos/proto_manufacturer.proto\"\214\001" +
      "\n\023ManufacturerRequest\022\024\n\014manufacturer\030\001 " +
      "\001(\t\022\017\n\007product\030\002 \001(\t\022\024\n\014min_quantity\030\003 \001" +
      "(\005\022\024\n\014max_quantity\030\004 \001(\005\022\021\n\tmin_price\030\005 " +
      "\001(\002\022\017\n\007seconds\030\006 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ManufacturerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ManufacturerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ManufacturerRequest_descriptor,
        new java.lang.String[] { "Manufacturer", "Product", "MinQuantity", "MaxQuantity", "MinPrice", "Seconds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
